"""Close a merged implementation Issue and release its execution lock.

The marker is written by the trusted implementation workflow into the generated
PR body. A human merge is the authorization boundary for this finalizer.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

try:
    from scripts.triage_conclusion import GitHubClient, TriageError, label_names
except ModuleNotFoundError:  # Running as ``python scripts/frontier_advance.py``.
    from triage_conclusion import GitHubClient, TriageError, label_names


TARGET_MARKER = re.compile(r"(?im)^\s*PH_AUTO_LABEL_TARGET:\s*issue:(\d+)\s*$")
MERGE_MARKER = "Implementation merged: "
EXECUTION_LABELS = {"agent-running", "ready-for-agent"}


def target_issue_number(event: dict[str, Any]) -> int | None:
    pull_request = event.get("pull_request", {})
    body = pull_request.get("body") if isinstance(pull_request, dict) else None
    if not isinstance(body, str):
        return None
    match = TARGET_MARKER.search(body)
    if not match:
        return None
    return int(match.group(1))


def merged_event_key(event: dict[str, Any]) -> str:
    pull_request = event.get("pull_request", {})
    number = pull_request.get("number")
    merge_sha = pull_request.get("merge_commit_sha") or "unknown"
    if not isinstance(number, int) or number < 1:
        raise TriageError("merged pull request number is invalid")
    if not isinstance(merge_sha, str) or not merge_sha:
        raise TriageError("merged pull request SHA is invalid")
    return f"pr:{number}:merge:{merge_sha}"


def run(event: dict[str, Any], client: GitHubClient) -> str:
    if event.get("action") != "closed":
        return "skipped: pull request is not closed"
    pull_request = event.get("pull_request", {})
    if not isinstance(pull_request, dict) or pull_request.get("merged") is not True:
        return "skipped: pull request was not merged"
    labels = {
        label.get("name")
        for label in pull_request.get("labels", [])
        if isinstance(label, dict) and isinstance(label.get("name"), str)
    }
    if "ai-generated" not in labels:
        return "skipped: pull request is not an implementation PR"
    issue_number = target_issue_number(event)
    if issue_number is None:
        return "skipped: implementation marker is missing"

    event_key = merged_event_key(event)
    item = client.get_issue_or_pr(issue_number)
    comments = client.list_comments(issue_number)
    if any(f"{MERGE_MARKER}{event_key}" in str(comment.get("body", "")) for comment in comments):
        return "skipped: merge event already processed"

    desired_labels = label_names(item) - EXECUTION_LABELS
    client.replace_labels(issue_number, desired_labels)
    client.add_comment(
        issue_number,
        "\n".join(
            [
                "> *This was generated by the trusted implementation finalizer.*",
                "",
                "The implementation Pull Request was merged. This execution Issue is complete.",
                "",
                f"{MERGE_MARKER}{event_key}",
            ]
        ),
    )
    if item.get("state") != "closed":
        client.close_item(issue_number)
    return "applied: issue closed and execution lock released"


def main() -> int:
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        print("GITHUB_EVENT_PATH is missing", file=sys.stderr)
        return 1
    try:
        event = json.loads(Path(event_path).read_text(encoding="utf-8"))
        client = GitHubClient(
            os.environ.get("GITHUB_TOKEN", os.environ.get("GH_TOKEN", "")),
            os.environ.get("GITHUB_API_URL", "https://api.github.com"),
            os.environ.get("GITHUB_REPOSITORY", ""),
        )
        print(run(event, client))
    except (OSError, json.JSONDecodeError, TriageError) as exc:
        print(f"frontier advance failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
