"""Validate and apply one native Matt triage result.

This is the trusted adapter for the native triage bridge. It is a write
gateway, not a second triage engine. Claude produces one structured result
``{category, state, reason, comment}`` read-only; this script decides exactly
what GitHub writes: category/state labels, one marked comment, and - only for
``wontfix`` - closure with ``state_reason: not_planned``. Nothing else.

It deliberately contains no confidence threshold, no fallback classification,
no implementation/agent dispatch, no Spec/Ticket routing and no transition
table. Invalid, stale, conflicting or unauthorized input fails closed with zero
GitHub mutations.

The script runs only in the trusted apply job checked out from the default
branch (``pull_request_target``). It never executes Issue/PR content.
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

MANAGED_CATEGORIES = frozenset({"bug", "enhancement"})
MANAGED_STATES = frozenset({"needs-triage", "needs-info", "ready-for-agent", "ready-for-human", "wontfix"})
MANAGED_LABELS = MANAGED_CATEGORIES | MANAGED_STATES

# External PR diff incomplete/absent: Claude must not claim full review, so
# only these two states may be applied. Everything else fails closed.
PR_PARTIAL_ACCEPT_STATES = frozenset({"needs-info", "ready-for-human"})

AI_DISCLAIMER = "> *This was generated by AI during triage.*"
MARKER_OPEN = "<!-- triage-automation v1"
MAX_REASON_LENGTH = 4000
MAX_COMMENT_LENGTH = 12000
EVENT_KEY_PATTERN = re.compile(r"^[A-Za-z0-9:_-]{1,300}$")
SHA_PATTERN = re.compile(r"^[0-9a-f]{7,64}$")

# Bounded skip/failure reason codes (safe for GITHUB_STEP_SUMMARY; never free text).
REASON_MALFORMED = "malformed_output"
REASON_STALE = "stale_head"
REASON_CONFLICT = "label_conflict"
REASON_DUPLICATE = "duplicate_event"
REASON_CONTEXT = "context_failure"
REASON_MUTATION = "mutation_failure"


class TriageError(ValueError):
    """A bounded, safe failure carrying a reason code."""

    def __init__(self, reason: str, message: str) -> None:
        super().__init__(message)
        self.reason = reason


@dataclass(frozen=True)
class Result:
    category: str
    state: str
    reason: str
    comment: str


@dataclass(frozen=True)
class Target:
    target_type: str
    number: int
    event_key: str
    head_sha: str


@dataclass(frozen=True)
class Mutation:
    op: str  # add_label | remove_label | add_comment | close
    name: str = ""
    body: str = ""


class GitHubClient:
    """Thin, stdlib-only GitHub Issues/Pull-Requests API client."""

    def __init__(self, token: str, api_url: str, repository: str) -> None:
        if not token:
            raise TriageError(REASON_CONTEXT, "GITHUB_TOKEN is missing")
        if not re.fullmatch(r"[^/\s]+/[^/\s]+", repository):
            raise TriageError(REASON_CONTEXT, "GITHUB_REPOSITORY is invalid")
        self.token = token
        self.base_url = api_url.rstrip("/")
        self.repository = repository

    def request(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
    ) -> Any:
        if not path.startswith("/") or ".." in path:
            raise TriageError(REASON_CONTEXT, "unsafe GitHub API path")
        body = None
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self.token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "ph-auto-label-triage",
        }
        if payload is not None:
            body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(f"{self.base_url}{path}", data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                raw = response.read()
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
            raise TriageError(REASON_MUTATION, f"GitHub API request failed: {method} {path}") from exc
        if not raw:
            return None
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise TriageError(REASON_CONTEXT, "GitHub API returned invalid JSON") from exc

    def get_issue_or_pr(self, number: int) -> dict[str, Any]:
        return self.request("GET", f"/repos/{self.repository}/issues/{number}")

    def get_pull_request(self, number: int) -> dict[str, Any]:
        return self.request("GET", f"/repos/{self.repository}/pulls/{number}")

    def pull_diff(self, number: int) -> str:
        """Fetch the combined PR diff; raises TriageError on failure."""
        path = f"/repos/{self.repository}/pulls/{number}"
        headers = {
            "Accept": "application/vnd.github.v3.diff",
            "Authorization": f"Bearer {self.token}",
            "User-Agent": "ph-auto-label-triage",
        }
        request = urllib.request.Request(f"{self.base_url}{path}", headers=headers, method="GET")
        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                return response.read().decode("utf-8", errors="replace")
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
            raise TriageError(REASON_CONTEXT, f"GitHub PR diff request failed: {path}") from exc

    def list_labels(self) -> list[dict[str, Any]]:
        result = self.request("GET", f"/repos/{self.repository}/labels?per_page=100")
        if not isinstance(result, list):
            raise TriageError(REASON_CONTEXT, "GitHub labels response is invalid")
        return result

    def collaborator_permission(self, login: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]*", login):
            raise TriageError(REASON_CONTEXT, "actor login is invalid")
        result = self.request("GET", f"/repos/{self.repository}/collaborators/{login}/permission")
        value = result.get("permission") if isinstance(result, dict) else None
        if not isinstance(value, str):
            raise TriageError(REASON_CONTEXT, "actor permission is unavailable")
        return value

    def list_comments(self, number: int) -> list[dict[str, Any]]:
        comments: list[dict[str, Any]] = []
        page = 1
        while True:
            result = self.request(
                "GET",
                f"/repos/{self.repository}/issues/{number}/comments?per_page=100&page={page}",
            )
            if not isinstance(result, list):
                raise TriageError(REASON_CONTEXT, "GitHub comments response is invalid")
            comments.extend(result)
            if len(result) < 100:
                return comments
            page += 1

    def add_label(self, number: int, name: str) -> None:
        self.request("POST", f"/repos/{self.repository}/issues/{number}/labels", {"labels": [name]})

    def remove_label(self, number: int, name: str) -> None:
        self.request("DELETE", f"/repos/{self.repository}/issues/{number}/labels/{name}")

    def add_comment(self, number: int, body: str) -> None:
        self.request("POST", f"/repos/{self.repository}/issues/{number}/comments", {"body": body})

    def close_item(self, number: int) -> None:
        self.request(
            "PATCH",
            f"/repos/{self.repository}/issues/{number}",
            {"state": "closed", "state_reason": "not_planned"},
        )


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise TriageError(REASON_MALFORMED, f"{field} must be a string")
    value = value.strip()
    if not value:
        raise TriageError(REASON_MALFORMED, f"{field} is required")
    return value


def validate_result(raw: Any) -> Result:
    """Parse and validate one native triage result. Fail closed on any deviation."""
    if not isinstance(raw, dict):
        raise TriageError(REASON_MALFORMED, "result is not an object")
    unknown = set(raw) - {"category", "state", "reason", "comment"}
    if unknown:
        raise TriageError(REASON_MALFORMED, f"result has unknown fields: {sorted(unknown)}")
    category = _string(raw.get("category"), "category")
    state = _string(raw.get("state"), "state")
    reason = _string(raw.get("reason"), "reason")
    comment = _string(raw.get("comment"), "comment")
    if category not in MANAGED_CATEGORIES:
        raise TriageError(REASON_MALFORMED, f"category is outside the allowlist: {category!r}")
    if state not in MANAGED_STATES:
        raise TriageError(REASON_MALFORMED, f"state is outside the allowlist: {state!r}")
    if len(reason) > MAX_REASON_LENGTH:
        raise TriageError(REASON_MALFORMED, "reason is too long")
    if not comment.startswith(AI_DISCLAIMER):
        raise TriageError(REASON_MALFORMED, "comment must begin with the native AI disclaimer")
    if len(comment) > MAX_COMMENT_LENGTH:
        raise TriageError(REASON_MALFORMED, "comment is too long")
    body = comment[len(AI_DISCLAIMER) :]
    # Per-state structural section contract (fail closed; no invented fallback).
    if state == "needs-info" and "?" not in body:
        raise TriageError(REASON_MALFORMED, "needs-info comment must contain concrete questions")
    if state in {"ready-for-agent", "ready-for-human"} and "## " not in body:
        raise TriageError(REASON_MALFORMED, "ready-for-* comment must contain an agent brief section")
    if state == "wontfix" and not reason:
        raise TriageError(REASON_MALFORMED, "wontfix requires a durable rejection reason")
    return Result(category=category, state=state, reason=reason, comment=comment)


def marker_for(result: Result, target: Target) -> str:
    lines = [
        MARKER_OPEN,
        f"event_key: {target.event_key}",
        f"target_type: {target.target_type}",
        f"target_number: {target.number}",
        f"head_sha: {target.head_sha or ''}",
        f"category: {result.category}",
        f"state: {result.state}",
        "-->",
    ]
    return "\n".join(lines)


def find_trusted_marker(comments: list[dict[str, Any]], writer_bot_id: str, event_key: str) -> bool:
    """A marker counts only when authored by the trusted writer bot.

    Similar text from a user is never a duplicate, so this check is author-bound.
    """
    for comment in comments:
        author_id = comment.get("user", {}).get("id")
        if str(author_id) != str(writer_bot_id):
            continue
        body = str(comment.get("body", ""))
        if MARKER_OPEN in body and f"event_key: {event_key}" in body:
            return True
    return False


def read_marker_result(comments: list[dict[str, Any]], writer_bot_id: str, event_key: str) -> Result | None:
    """Rebuild a minimal Result from a trusted marker for reconcile-only replays.

    The marker records category/state; reason/comment are left empty because the
    marker's presence guarantees the triage comment already exists, so the
    marker-tagged run only reconciles labels and close, never re-comments.
    """
    for comment in comments:
        author_id = comment.get("user", {}).get("id")
        if str(author_id) != str(writer_bot_id):
            continue
        body = str(comment.get("body", ""))
        if MARKER_OPEN not in body or f"event_key: {event_key}" not in body:
            continue
        lines = body.splitlines()
        fields: dict[str, str] = {}
        for line in lines[1:]:
            if ":" in line and not line.startswith("<!--") and "-->" not in line:
                key, _, value = line.partition(":")
                fields[key.strip()] = value.strip()
        category = fields.get("category", "")
        state = fields.get("state", "")
        if category not in MANAGED_CATEGORIES or state not in MANAGED_STATES:
            raise TriageError(REASON_MALFORMED, "trusted marker has invalid category/state")
        return Result(category=category, state=state, reason="", comment="")
    return None


def label_names(item: dict[str, Any]) -> set[str]:
    return {
        label.get("name")
        for label in item.get("labels", [])
        if isinstance(label, dict) and isinstance(label.get("name"), str)
    }


def plan_mutations(
    result: Result,
    *,
    target: Target,
    current_head: str | None,
    labels: set[str],
    comments: list[dict[str, Any]],
    writer_bot_id: str,
    open_state: bool,
    diff_complete: bool,
) -> list[Mutation]:
    """Compute the exact ordered GitHub writes, or fail closed with zero writes."""
    if target.target_type == "pull_request":
        if not current_head:
            raise TriageError(REASON_CONTEXT, "pull request head SHA is unavailable")
        if target.head_sha and current_head != target.head_sha:
            raise TriageError(REASON_STALE, "pull request head changed since triage")
        if not diff_complete and result.state not in PR_PARTIAL_ACCEPT_STATES:
            raise TriageError(
                REASON_CONTEXT,
                f"incomplete external PR diff cannot accept state {result.state!r}",
            )

    categories = labels & MANAGED_CATEGORIES
    states = labels & MANAGED_STATES
    if len(categories) > 1:
        raise TriageError(REASON_CONFLICT, "conflicting managed category labels present")
    if len(states) > 1:
        raise TriageError(REASON_CONFLICT, "conflicting managed state labels present")

    desired_cat = result.category
    desired_state = result.state
    mutations: list[Mutation] = []
    # Reconcile labels independently; never touch unrelated labels.
    for name in sorted(categories - {desired_cat}):
        mutations.append(Mutation("remove_label", name=name))
    for name in sorted(states - {desired_state}):
        mutations.append(Mutation("remove_label", name=name))
    if desired_cat not in labels:
        mutations.append(Mutation("add_label", name=desired_cat))
    if desired_state not in labels:
        mutations.append(Mutation("add_label", name=desired_state))
    # Add the marked comment only when the exact trusted marker is absent.
    if not find_trusted_marker(comments, writer_bot_id, target.event_key):
        mutations.append(Mutation("add_comment", body=f"{result.comment}\n\n{marker_for(result, target)}"))
    # Close only for wontfix, only when currently open.
    if result.state == "wontfix" and open_state:
        mutations.append(Mutation("close"))
    return mutations


def apply_mutations(client: GitHubClient, number: int, mutations: list[Mutation]) -> None:
    for mutation in mutations:
        if mutation.op == "add_label":
            client.add_label(number, mutation.name)
        elif mutation.op == "remove_label":
            client.remove_label(number, mutation.name)
        elif mutation.op == "add_comment":
            client.add_comment(number, mutation.body)
        elif mutation.op == "close":
            client.close_item(number)
        else:  # pragma: no cover - defensive; apply is the only caller
            raise TriageError(REASON_CONTEXT, f"unknown mutation op {mutation.op!r}")


def derive_event_key(event_name: str, event: dict[str, Any]) -> Target:
    """Derive the trusted target/event identity from the raw GitHub event.

    Serves the preflight gate. Unrecognized trigger shapes fail closed.
    """
    if event_name == "issues":
        action = event.get("action")
        issue = event.get("issue", {})
        number = issue.get("number")
        timestamp = issue.get("created_at") if action == "opened" else issue.get("updated_at")
        if action in {"opened", "reopened"} and isinstance(number, int) and isinstance(timestamp, str) and timestamp:
            return Target("issue", number, f"issue:{number}:{action}:{timestamp}", "")
    if event_name == "issue_comment" and event.get("action") == "created":
        issue = event.get("issue", {})
        comment = event.get("comment", {})
        number = issue.get("number")
        comment_id = comment.get("id")
        if isinstance(number, int) and isinstance(comment_id, int):
            target_type = "pr" if isinstance(issue.get("pull_request"), dict) else "issue"
            return Target(target_type, number, f"comment:{comment_id}:created", "")
    if event_name == "pull_request_target":
        action = event.get("action")
        pull_request = event.get("pull_request", {})
        number = pull_request.get("number")
        head_sha = pull_request.get("head", {}).get("sha")
        if (
            action in {"opened", "reopened", "synchronize"}
            and isinstance(number, int)
            and isinstance(head_sha, str)
            and SHA_PATTERN.fullmatch(head_sha)
        ):
            return Target("pr", number, f"pr:{number}:{action}:{head_sha}", head_sha)
    raise TriageError(REASON_CONTEXT, "event is outside the triage trigger contract")


def decide_preflight(
    event_name: str,
    event: dict[str, Any],
    *,
    client: GitHubClient,
    writer_bot_id: str,
) -> dict[str, Any]:
    """Deterministic preflight gate. Read-only; never mutates.

    Returns run/analyze/reconcile flags, the trusted identity the downstream
    apply job consumes, and a bounded reason code when the event is skipped.
    A skip here means zero Claude invocation and zero GitHub writes.
    """
    empty = {
        "run": False,
        "analyze": False,
        "reconcile": False,
        "reason": "",
        "target_type": "",
        "target_number": 0,
        "event_key": "",
        "head_sha": "",
    }

    sender = event.get("sender", {})
    if isinstance(sender, dict) and sender.get("type") in {"Bot", "App"}:
        return dict(empty, reason="bot")
    try:
        target = derive_event_key(event_name, event)
    except TriageError:
        return dict(empty, reason="untriggered_event")

    # The only authorized write-capable request surface is Issue/PR `/triage`.
    if event_name == "issue_comment":
        body = str(event.get("comment", {}).get("body", ""))
        if "/triage" not in body:
            return dict(
                empty,
                target_type=target.target_type,
                target_number=target.number,
                event_key=target.event_key,
                reason="ordinary_issue_comment",
            )
        login = sender.get("login")
        permission = client.collaborator_permission(str(login)) if isinstance(login, str) else ""
        if permission not in {"write", "admin"}:
            return dict(
                empty,
                target_type=target.target_type,
                target_number=target.number,
                event_key=target.event_key,
                reason="unauthorized_triage_command",
            )

    if event_name == "pull_request_target":
        pull_request = event.get("pull_request", {})
        association = pull_request.get("author_association")
        head_repo_id = pull_request.get("head", {}).get("repo", {}).get("id")
        base_repo_id = event.get("repository", {}).get("id")
        is_external = (
            association in {"CONTRIBUTOR", "FIRST_TIME_CONTRIBUTOR", "NONE"}
            and isinstance(head_repo_id, int)
            and head_repo_id != base_repo_id
        )
        if not is_external:
            return dict(
                empty,
                target_type=target.target_type,
                target_number=target.number,
                event_key=target.event_key,
                head_sha=target.head_sha,
                reason="ineligible_pr",
            )

    managed_here = {label.get("name") for label in client.list_labels() if isinstance(label, dict)}
    missing = MANAGED_LABELS - managed_here
    if missing:
        return dict(
            empty,
            target_type=target.target_type,
            target_number=target.number,
            event_key=target.event_key,
            head_sha=target.head_sha,
            reason="missing_label",
        )

    if find_trusted_marker(client.list_comments(target.number), writer_bot_id, target.event_key):
        return dict(
            empty,
            run=True,
            reconcile=True,
            reason="marker_found",
            target_type=target.target_type,
            target_number=target.number,
            event_key=target.event_key,
            head_sha=target.head_sha,
        )

    return dict(
        empty,
        run=True,
        analyze=True,
        target_type=target.target_type,
        target_number=target.number,
        event_key=target.event_key,
        head_sha=target.head_sha,
    )


def load_result(path: str | None) -> Result:
    if not path:
        raise TriageError(REASON_MALFORMED, "TRIAGE_RESULT_PATH is missing")
    try:
        raw = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise TriageError(REASON_MALFORMED, "structured result is unreadable or invalid JSON") from exc
    return validate_result(raw)


def _env_string(name: str, *, required: bool = True) -> str:
    value = os.environ.get(name, "").strip()
    if required and not value:
        raise TriageError(REASON_CONTEXT, f"{name} is missing")
    return value


def run(
    client: GitHubClient,
    *,
    result_path: str | None,
    target_type: str,
    target_number: int,
    event_key: str,
    head_sha: str,
    diff_complete: bool,
    writer_bot_id: str,
) -> str:
    if target_type not in {"issue", "pr"}:
        raise TriageError(REASON_CONTEXT, "TRIAGE_TARGET_TYPE is invalid")
    if target_number < 1:
        raise TriageError(REASON_CONTEXT, "TRIAGE_TARGET_NUMBER must be positive")
    if not EVENT_KEY_PATTERN.fullmatch(event_key):
        raise TriageError(REASON_CONTEXT, "TRIAGE_EVENT_KEY is invalid")
    if head_sha and not SHA_PATTERN.fullmatch(head_sha):
        raise TriageError(REASON_CONTEXT, "TRIAGE_HEAD_SHA is invalid")

    target = Target(target_type, target_number, event_key, head_sha)
    current_head: str | None = None
    if target_type == "pr":
        pull_request = client.get_pull_request(target_number)
        current = pull_request.get("head", {}).get("sha")
        if not isinstance(current, str) or not SHA_PATTERN.fullmatch(current):
            raise TriageError(REASON_CONTEXT, "pull request has no valid current head SHA")
        current_head = current

    item = client.get_issue_or_pr(target_number)
    labels = label_names(item)
    comments = client.list_comments(target_number)
    result = (
        load_result(result_path)
        if result_path
        else read_marker_result(comments, writer_bot_id, event_key)
    )
    if result is None:
        raise TriageError(REASON_CONTEXT, "no triage result and no trusted marker to reconcile")
    mutations = plan_mutations(
        result,
        target=target,
        current_head=current_head,
        labels=labels,
        comments=comments,
        writer_bot_id=writer_bot_id,
        open_state=item.get("state") == "open",
        diff_complete=diff_complete,
    )
    if not mutations:
        # Marker already present and labels/close already reconciled: no-op replay.
        return "skipped: duplicate_event"
    apply_mutations(client, target_number, mutations)
    return "applied"


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN", "")
    api_url = os.environ.get("GITHUB_API_URL", "https://api.github.com")
    repository = os.environ.get("GITHUB_REPOSITORY", "")
    path = os.environ.get("TRIAGE_RESULT_PATH")
    # Reconcile-only replays skip the analyze job and produce no result file;
    # an absent file falls back to rebuilding the result from the trusted marker.
    if path and not os.path.exists(path):
        path = None
    try:
        client = GitHubClient(token, api_url, repository)
        result = run(
            client,
            result_path=path,
            target_type=_env_string("TRIAGE_TARGET_TYPE"),
            target_number=int(os.environ.get("TRIAGE_TARGET_NUMBER", "0")),
            event_key=_env_string("TRIAGE_EVENT_KEY"),
            head_sha=_env_string("TRIAGE_HEAD_SHA", required=False),
            diff_complete=os.environ.get("TRIAGE_DIFF_COMPLETE", "").strip().lower() == "true",
            writer_bot_id=_env_string("TRIAGE_WRITER_BOT_ID", required=False),
        )
    except TriageError as exc:
        print(f"triage adapter failed: {exc.reason}", file=sys.stderr)
        return 2
    except (ValueError, OSError):
        print(f"triage adapter failed: {REASON_CONTEXT}", file=sys.stderr)
        return 2
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
