"""Validate and apply one gh-aw triage decision.

The script runs only in a trusted post-agent job checked out from the default
branch. It deliberately does not execute any content from an Issue or PR.
"""

from __future__ import annotations

import json
import math
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any


MANAGED_CATEGORIES = frozenset({"bug", "enhancement"})
MANAGED_STATES = frozenset(
    {"needs-triage", "needs-info", "ready-for-agent", "ready-for-human", "wontfix"}
)
MANAGED_LABELS = MANAGED_CATEGORIES | MANAGED_STATES
AI_DISCLAIMER = "> *This was generated by AI during triage.*"
EVENT_FOOTER_PREFIX = "Triage event: "
CONFIDENCE_THRESHOLD = 0.75
MAX_REASON_LENGTH = 4000
MAX_MISSING_ITEMS = 20
MAX_MISSING_LENGTH = 500
MAX_COMMENT_LENGTH = 12000
EVENT_KEY_PATTERN = re.compile(r"^[A-Za-z0-9:_-]{1,300}$")
SHA_PATTERN = re.compile(r"^[0-9a-f]{7,64}$")


class TriageError(ValueError):
    """A safe, user-facing validation failure."""


@dataclass(frozen=True)
class Decision:
    schema_version: int
    target_type: str
    target_number: int
    event_key: str
    head_sha: str
    category: str
    state: str
    confidence: float
    reason: str
    missing_info: tuple[str, ...]


@dataclass(frozen=True)
class Target:
    target_type: str
    number: int
    event_key: str
    head_sha: str


class GitHubClient:
    def __init__(self, token: str, api_url: str, repository: str) -> None:
        if not token:
            raise TriageError("GITHUB_TOKEN is missing")
        if not re.fullmatch(r"[^/\s]+/[^/\s]+", repository):
            raise TriageError("GITHUB_REPOSITORY is invalid")
        self.token = token
        self.base_url = api_url.rstrip("/")
        self.repository = repository

    def request(self, method: str, path: str, payload: dict[str, Any] | None = None) -> Any:
        if not path.startswith("/") or ".." in path:
            raise TriageError("unsafe GitHub API path")
        body = None
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self.token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "ph-auto-label-triage",
        }
        if payload is not None:
            body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(
            f"{self.base_url}{path}", data=body, headers=headers, method=method
        )
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                raw = response.read()
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
            raise TriageError(f"GitHub API request failed: {method} {path}") from exc
        if not raw:
            return None
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise TriageError("GitHub API returned invalid JSON") from exc

    def get_issue_or_pr(self, number: int) -> dict[str, Any]:
        return self.request("GET", f"/repos/{self.repository}/issues/{number}")

    def get_pull_request(self, number: int) -> dict[str, Any]:
        return self.request("GET", f"/repos/{self.repository}/pulls/{number}")

    def list_comments(self, number: int) -> list[dict[str, Any]]:
        comments: list[dict[str, Any]] = []
        for page in range(1, 11):
            result = self.request(
                "GET",
                f"/repos/{self.repository}/issues/{number}/comments?per_page=100&page={page}",
            )
            if not isinstance(result, list):
                raise TriageError("GitHub comments response is invalid")
            comments.extend(result)
            if len(result) < 100:
                return comments
        return comments

    def add_label(self, number: int, label: str) -> None:
        self.request("POST", f"/repos/{self.repository}/issues/{number}/labels", {"labels": [label]})

    def remove_label(self, number: int, label: str) -> None:
        encoded = urllib.parse.quote(label, safe="")
        self.request("DELETE", f"/repos/{self.repository}/issues/{number}/labels/{encoded}")

    def add_comment(self, number: int, body: str) -> None:
        self.request("POST", f"/repos/{self.repository}/issues/{number}/comments", {"body": body})


def _string(value: Any, field: str, *, required: bool = True) -> str:
    if not isinstance(value, str):
        raise TriageError(f"{field} must be a string")
    value = value.strip()
    if required and not value:
        raise TriageError(f"{field} is required")
    return value


def parse_decision(item: dict[str, Any]) -> Decision:
    if not isinstance(item, dict):
        raise TriageError("decision is not an object")
    try:
        schema_version = int(item.get("schema_version"))
        target_number = int(item.get("target_number"))
        confidence = float(item.get("confidence"))
    except (TypeError, ValueError) as exc:
        raise TriageError("schema_version, target_number, or confidence is invalid") from exc
    target_type = _string(item.get("target_type"), "target_type")
    event_key = _string(item.get("event_key"), "event_key")
    head_sha = _string(item.get("head_sha", ""), "head_sha", required=False)
    category = _string(item.get("category"), "category")
    state = _string(item.get("state"), "state")
    reason = _string(item.get("reason"), "reason")
    raw_missing = item.get("missing_info", "[]")
    if isinstance(raw_missing, str):
        try:
            raw_missing = json.loads(raw_missing)
        except json.JSONDecodeError as exc:
            raise TriageError("missing_info is not valid JSON") from exc
    if not isinstance(raw_missing, list) or len(raw_missing) > MAX_MISSING_ITEMS:
        raise TriageError("missing_info must be a bounded array")
    missing_info = tuple(_string(value, "missing_info item") for value in raw_missing)
    if any(len(value) > MAX_MISSING_LENGTH for value in missing_info):
        raise TriageError("missing_info item is too long")
    if schema_version != 1:
        raise TriageError("unsupported schema_version")
    if target_type not in {"issue", "pull_request"}:
        raise TriageError("unsupported target_type")
    if target_number < 1:
        raise TriageError("target_number must be positive")
    if not EVENT_KEY_PATTERN.fullmatch(event_key):
        raise TriageError("event_key is invalid")
    if head_sha and not SHA_PATTERN.fullmatch(head_sha):
        raise TriageError("head_sha is invalid")
    if category not in MANAGED_CATEGORIES or state not in MANAGED_STATES:
        raise TriageError("category or state is outside the allowlist")
    if not math.isfinite(confidence) or not 0 <= confidence <= 1:
        raise TriageError("confidence must be between 0 and 1")
    if len(reason) > MAX_REASON_LENGTH:
        raise TriageError("reason is too long")
    if target_type == "pull_request" and not head_sha:
        raise TriageError("pull_request decisions require head_sha")
    if target_type == "issue" and head_sha:
        raise TriageError("issue decisions must not contain head_sha")
    return Decision(
        schema_version=schema_version,
        target_type=target_type,
        target_number=target_number,
        event_key=event_key,
        head_sha=head_sha,
        category=category,
        state=state,
        confidence=confidence,
        reason=reason,
        missing_info=missing_info,
    )


def load_agent_decision(path: str | None) -> Decision | None:
    if not path:
        return None
    try:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    items = payload.get("items") if isinstance(payload, dict) else None
    if not isinstance(items, list):
        return None
    candidates = [
        item
        for item in items
        if isinstance(item, dict) and item.get("type") in {"apply_triage", "apply-triage"}
    ]
    if len(candidates) != 1:
        return None
    try:
        return parse_decision(candidates[0])
    except TriageError:
        return None


def _repository_id(event: dict[str, Any]) -> int | None:
    value = event.get("repository", {}).get("id")
    return value if isinstance(value, int) else None


def derive_target(event_name: str, event: dict[str, Any], current_pr: dict[str, Any] | None = None) -> Target:
    if event_name == "issues" and event.get("action") == "opened":
        issue = event.get("issue", {})
        number = issue.get("number")
        created_at = issue.get("created_at")
        if isinstance(number, int) and isinstance(created_at, str) and created_at:
            return Target("issue", number, f"issue:{number}:opened:{created_at}", "")
    if event_name == "issue_comment" and event.get("action") == "created":
        issue = event.get("issue", {})
        comment = event.get("comment", {})
        number = issue.get("number")
        comment_id = comment.get("id")
        if isinstance(number, int) and isinstance(comment_id, int):
            target_type = "pull_request" if isinstance(issue.get("pull_request"), dict) else "issue"
            return Target(target_type, number, f"comment:{comment_id}:created", "")
    if event_name == "workflow_run":
        run = event.get("workflow_run", {})
        if (
            event.get("action") == "completed"
            and run.get("name") == "CI"
            and run.get("event") == "pull_request"
            and _repository_id(event) == run.get("repository", {}).get("id")
        ):
            pull_requests = run.get("pull_requests")
            if isinstance(pull_requests, list) and len(pull_requests) == 1:
                association = pull_requests[0]
                number = association.get("number") if isinstance(association, dict) else None
                head_sha = run.get("head_sha")
                if isinstance(number, int) and isinstance(head_sha, str) and SHA_PATTERN.fullmatch(head_sha):
                    return Target("pull_request", number, f"pr:{number}:sha:{head_sha}", head_sha)
    if event_name == "pull_request_target":
        pull_request = event.get("pull_request", {})
        number = pull_request.get("number")
        head_sha = pull_request.get("head", {}).get("sha")
        head_repo_id = pull_request.get("head", {}).get("repo", {}).get("id")
        base_repo_id = event.get("repository", {}).get("id")
        action = event.get("action")
        if (
            action in {"opened", "synchronize"}
            and isinstance(number, int)
            and isinstance(head_sha, str)
            and SHA_PATTERN.fullmatch(head_sha)
            and isinstance(head_repo_id, int)
            and isinstance(base_repo_id, int)
            and head_repo_id != base_repo_id
        ):
            return Target("pull_request", number, f"pr:{number}:sha:{head_sha}", head_sha)
    raise TriageError("event is outside the triage trigger contract")


def is_bot_or_system(event_name: str, event: dict[str, Any]) -> bool:
    if event_name == "issues":
        issue = event.get("issue", {})
        user = issue.get("user", {})
        issue_labels = {
            label.get("name")
            for label in issue.get("labels", [])
            if isinstance(label, dict) and isinstance(label.get("name"), str)
        }
        return user.get("type") == "Bot" or "agentic-workflows" in issue_labels
    if event_name == "issue_comment":
        comment = event.get("comment", {})
        return comment.get("user", {}).get("type") == "Bot"
    return False


def label_names(item: dict[str, Any]) -> set[str]:
    return {
        label.get("name")
        for label in item.get("labels", [])
        if isinstance(label, dict) and isinstance(label.get("name"), str)
    }


def validate_target(decision: Decision, target: Target, item: dict[str, Any]) -> None:
    if decision.target_type != target.target_type or decision.target_number != target.number:
        raise TriageError("decision target does not match the event")
    if decision.event_key != target.event_key:
        raise TriageError("decision event_key does not match the event")
    if target.target_type == "pull_request" and decision.head_sha != target.head_sha:
        raise TriageError("decision head_sha does not match the event")
    if target.target_type == "issue" and decision.head_sha:
        raise TriageError("issue decision contains a head_sha")
    if "triage-paused" in label_names(item):
        raise TriageError("triage is paused for this item")


def validate_transition(decision: Decision, item: dict[str, Any]) -> None:
    categories = label_names(item) & MANAGED_CATEGORIES
    states = label_names(item) & MANAGED_STATES
    if len(categories) > 1:
        raise TriageError("item has conflicting managed category labels")
    if len(states) > 1:
        raise TriageError("item has conflicting managed state labels")
    current = next(iter(states), None)
    if current == "needs-triage" and decision.state == "needs-triage":
        raise TriageError("needs-triage must transition to an evaluated state")
    if current == "wontfix" and decision.state != "needs-triage":
        raise TriageError("wontfix may only transition to needs-triage")


def comment_body(decision: Decision, *, fallback_reason: str | None = None) -> str:
    reason = fallback_reason or decision.reason
    lines = [AI_DISCLAIMER, "", "## Automated triage", "", reason]
    if decision.missing_info:
        lines.extend(["", "Missing information:"])
        lines.extend(f"- {value}" for value in decision.missing_info)
    if decision.category:
        lines.extend(["", f"Category: `{decision.category}`"])
    lines.extend(["", f"State: `{decision.state}`"])
    footer = f"{EVENT_FOOTER_PREFIX}{decision.event_key}"
    prefix = "\n".join(lines)
    available = MAX_COMMENT_LENGTH - len(footer) - 2
    return f"{prefix[:available]}\n\n{footer}"


def fallback_decision(target: Target, item: dict[str, Any], reason: str) -> Decision:
    categories = label_names(item) & MANAGED_CATEGORIES
    category = next(iter(categories), "") if len(categories) == 1 else ""
    return Decision(
        schema_version=1,
        target_type=target.target_type,
        target_number=target.number,
        event_key=target.event_key,
        head_sha=target.head_sha,
        category=category,
        state="needs-triage",
        confidence=0.0,
        reason=reason,
        missing_info=(),
    )


def apply_decision(client: GitHubClient, decision: Decision, item: dict[str, Any]) -> None:
    current_labels = label_names(item)
    for label in sorted(current_labels & MANAGED_LABELS):
        client.remove_label(decision.target_number, label)
    if decision.category:
        client.add_label(decision.target_number, decision.category)
    client.add_label(decision.target_number, decision.state)
    client.add_comment(decision.target_number, comment_body(decision))


def already_processed(comments: list[dict[str, Any]], event_key: str) -> bool:
    marker = f"{EVENT_FOOTER_PREFIX}{event_key}"
    return any(marker in str(comment.get("body", "")) for comment in comments)


def run(event_name: str, event: dict[str, Any], client: GitHubClient, agent_path: str | None) -> str:
    if is_bot_or_system(event_name, event):
        return "skipped: bot or system event"
    target = derive_target(event_name, event)
    if target.target_type == "pull_request" and not target.head_sha:
        comment_pr = client.get_pull_request(target.number)
        comment_sha = comment_pr.get("head", {}).get("sha")
        if not isinstance(comment_sha, str) or not SHA_PATTERN.fullmatch(comment_sha):
            raise TriageError("PR comment has no valid current head SHA")
        target = Target(target.target_type, target.number, target.event_key, comment_sha)
    item = client.get_issue_or_pr(target.number)
    labels = label_names(item)
    if "triage-paused" in labels:
        return "skipped: triage-paused"
    comments = client.list_comments(target.number)
    if already_processed(comments, target.event_key):
        return "skipped: event already processed"
    if target.target_type == "pull_request":
        pull_request = client.get_pull_request(target.number)
        current_sha = pull_request.get("head", {}).get("sha")
        if current_sha != target.head_sha:
            return "skipped: stale pull request head"
        item = pull_request
    decision = load_agent_decision(agent_path)
    fallback_reason = None
    if decision is None:
        fallback_reason = "The triage model did not return one valid structured decision. Human review is required."
        decision = fallback_decision(target, item, fallback_reason)
    else:
        try:
            validate_target(decision, target, item)
            validate_transition(decision, item)
            if decision.confidence < CONFIDENCE_THRESHOLD:
                raise TriageError("confidence is below the configured threshold")
        except TriageError as exc:
            fallback_reason = f"Automated triage was routed to human review: {exc}."
            decision = fallback_decision(target, item, fallback_reason)
    apply_decision(client, decision, item)
    return "applied: fallback" if fallback_reason else "applied: decision"


def main() -> int:
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        print("GITHUB_EVENT_PATH is missing", file=sys.stderr)
        return 1
    try:
        event = json.loads(Path(event_path).read_text(encoding="utf-8"))
        event_name = os.environ.get("GITHUB_EVENT_NAME", "")
        client = GitHubClient(
            os.environ.get("GITHUB_TOKEN", os.environ.get("GH_TOKEN", "")),
            os.environ.get("GITHUB_API_URL", "https://api.github.com"),
            os.environ.get("GITHUB_REPOSITORY", ""),
        )
        result = run(event_name, event, client, os.environ.get("GH_AW_AGENT_OUTPUT"))
    except (OSError, json.JSONDecodeError, TriageError) as exc:
        print(f"triage conclusion failed: {exc}", file=sys.stderr)
        return 1
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
